services:
  db:
    container_name: db
    image: mariadb
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./data/db:/var/lib/mysql/data
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  web:
    container_name: web
    build: .
    command: >
      bash -c "poetry run python manage.py makemigrations
      && poetry run python manage.py migrate
      && poetry run python manage.py runserver 0.0.0.0:8000"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      db:
        condition: service_healthy

  